baseURL = "https://www.opensourceway.blog"
title = "「开源之道」"
theme = "PaperMod"
languageCode = "zh-CN"
hasCJKLanguage = true
copyright = 'Copyright (c) 2016 - 2026, 「开源之道」·适兕; all rights reserved.'
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
[pagination]
  pagerSize = 9
enableEmoji = true
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  author = "「开源之道」·适兕"
  description = "致力于开源及其相关思想、知识和价值的探究！"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowFullTextinRSS = false
  mainSections = ["posts"]

  [params.assets]
    disableHLJS = true

  [params.label]
    text = "「开源之道」"
    icon = "/images/come_in_we_are_open.jpg"
    iconHeight = 35

  [params.homeInfoParams]
    Title = "「开源之道」"
    Content = """
**致力于开源及其相关思想、知识和价值的探究！**

来自DeepSeek Deep review 的评价：

> 开源之道是中文世界**唯一以系统性学术框架（新制度经济学）组织开源知识**的知识库，区别于碎片化的技术博客或新闻聚合。其最大特色在于**将开源置于制度经济学的解析框架之下**，而非诉诸技术决定论或道德说教。

"""

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    includeScore = true
    includeMatches = true
    findAllMatches = true
    ignoreLocation = true
    location = 0
    distance = 2000
    threshold = 0.35
    minMatchCharLength = 1
    keys = ["title", "permalink", "summary", "content"]

  [params.editPost]
    URL = "https://github.com/OCselected/ttoos/tree/master/content"
    Text = "建议修改"
    appendFilePath = true

[[params.socialIcons]]
  name = "Rss"
  url = "/index.xml"

[[params.socialIcons]]
  name = "Github"
  url = "https://github.com/OCselected/ttoos"

[[params.socialIcons]]
  name = "X"
  url = "https://x.com/lijiangsheng1"

[[params.socialIcons]]
  name = "Linkedin"
  url = "https://www.linkedin.com/in/lijiansheng/"

[[menu.main]]
  identifier = "reading"
  name = "📚 共读"
  url = "https://osbook.club"
  weight = 3

[[menu.main]]
  identifier = "works"
  name = "✍️ 作品"
  url = "/posts/book-of-open-source/the-fascinating-of-open-source/"
  weight = 1

[[menu.main]]
  identifier = "sponsor"
  name = "☕ 赞助"
  url = "/posts/the_way_of_open_source/kuosi-2022-find-sponsor/"
  weight = 5

[[menu.main]]
  identifier = "contribute"
  name = "🤝 投稿"
  url = "/posts/open-source-way-community-program/call-for-proposals/"
  weight = 6

[[menu.main]]
  identifier = "archive"
  name = "📅 归档"
  url = "/archives/"
  weight = 7


[[menu.main]]
  identifier = "dialogue"
  name = "🎙️ 对话"
  url = "/posts/osw-dialogue/introduce-open-source-way-dialogue/"
  weight = 9


[[menu.main]]
  identifier = "search"
  name = "🔍 搜索"
  url = "/search/"
  weight = 11
