name: Hugo deploy

on:
  push:
    branches:
      - papermod-theme  # test branch for PaperMod theme deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false  # PaperMod is committed directly

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.155.1'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/papermod-theme'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: OCselected/ocselected.github.io
          publish_dir: ./public
          cname: opensourceway.blog
          publish_branch: gh-pages
          allow_empty_commit: true