# This is a basic workflow to help you get started with Actions

name: hugo deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@master
#        with:
#           submodules: true
      # 设置hugo环境
      - name: Setup Hugo
        run: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.83.1'
#            extended: true

      # 编译markdown
      - name: Build
        run: hugo --minify

      # 部署
      - name: deploy
        run: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: OCselected/ocselected.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public     
